### ISSUE TITLE
./athena-start start utf8_u2g 报错

### ISSUE THREAD

**Issue by zhqfdn** [CairoLee/rAthenaCN_Server#13]
[Fatal Error]: utf8_u2g: iconv was failed: Invalid or incomplete multibyte or wide character
[Fatal Error]: utf8_u2g: the strUtf8 param value: // MDEF‚ same as above. (MDEF * value)

**Comment by CairoLee** [comment]
## 解决方案

请确保全部使用 rAthenaCN 的 conf/battle 档案，若使用 rAthenaCN 的程序加上 rAthena 官方的配置文件的话，此问题就会出现。

## 问题原因

在 rAthena 官方的 `conf/battle/battle.conf` 配置文件中，可以看到这个配置文件的编码和其他的配置不太一样，其他的配置文件都是 ANSI 编码，而 battle.conf 是 UTF8 编码~ 这是为啥？

因为他里面拥有非 ANSI 的字符串，如果你把整个文件用 Notepad++ 转换到 ANSI 编码的话，会看到位于第 101 行附近的一下代码中，`MDEF`紧跟着的`逗号`变成了`?`乱码标识符：

```
// MDEF, same as above. (MDEF * value)
magic_defense_type: 0
```

所以实际上这个`,`是个：非 ANSI 编码下的一个长得像逗号的字符，而不是我们常规键盘上打出来的英文逗号。rAthenaCN 的在支持读取 UTF8-BOM 编码类型的配置文件时，暴露了此问题（因为基本原理是读取 UTF8-BOM 内容然后在内存中转回 GBK 等`单字节字符串`），转换的时候碰到了这个“假逗号”，而这货在 GBK 编码里面不存在，所以就报错了。

> 这个其实不能怪 rAthena，毕竟全球使用不同语言的人都在给 rAthena 贡献自己的劳动，在他们国家语言的字符集下，不小心用了一个非ANSI字符很正常，只是 rAthena 的程序没触发这个问题罢了。

## 可以不报错么？

为了不报错，在 https://github.com/CairoLee/rAthenaCN_Server/commit/ac89ed497823420a2266e0ace14995d25a0758dd#diff-c861cb68eadb0408c3c20bb633904e69 中进行过一次修正，把这个逗号改成正常的逗号了~ 所以请一定要确保配套使用。

最早思考的是：若遇到类似的编码问题存在于脚本中，那么暴露出来总是好的，这样可以确保不出现其他的意外情况。不过其实可以做的更好，如果发现转换错误的所在行是一句注释行，那么忽略即可。

后面可能会尝试这么调整一下，加强程序的稳定性。

**Comment by CairoLee** [comment]
已经在 a04a17e1c47f4c43d4046a223d4313d02251e881 中进行了一点小修改，如果遇到注释行则跳过 utf8_to_gbk 的操作。

**Comment by zhqfdn** [comment]
测试已经OK
