### ISSUE TITLE
设置  item_db, mob_db and mob_skill_db 从数据库读取后 @reloadmobdb 无效。

### ISSUE THREAD

**Issue by zhqfdn** [CairoLee/rAthenaCN_Server#15]
// Use SQL item_db, mob_db and mob_skill_db for the map server? (yes/no)
use_sql_db: yes

当设置  item_db, mob_db and mob_skill_db 从数据库读取后 @reloadmobdb 无效。

使用 @reloadmobdb 显示提示加载成功，实际 mob_db 数据并未重载， item_db 或  mob_skill_db 应该也是这样的情况。

**Comment by CairoLee** [comment]
## 测试结果

根据你描述的问题，我做了一下测试，目前看来确实有点奇怪~

## 测试步骤

1. 导入全新的英文 mob_db_re 库
2. 启动服务端，进入游戏
3. 使用 @mobinfo 1002 查看波利的名字，全英文
4. 修改数据库中 1002 魔物的 iName 和 jName（都测试一下）
5. 游戏里 @reloadmobdb
6. 重新使用 @mobinfo 1002 查看，里面返回结果有变化
7. 此时观察附近的魔物魔物，名字没变化
> 第 7 步这里是符合预期的，因为客户端对已经出现的 bl 对象，有缓存它的名称
8. 用 @monster 1002 召唤一个魔物，名字有变化，已经是最新的魔物名
> 第 8 步的结果说明此时服务端其实可以拿到最新的魔物名称
9. 然后用 @reloadscript 干掉所有魔物，此时观察被重新刷出来的魔物，名字还是 Poring
> 第 9 步的结果不符合预期，按道理应该已经变成新的魔物名称才对

## 问题分级

低优先，应该是什么地方有缓存，回头看下~

**Comment by CairoLee** [comment]
进一步测试发现，无论是否为 SQL 的 mob_db 数据，都存在一样的问题~

**Comment by zhqfdn** [comment]
哪就和数据读取没关系，应该问是在缓存上

**Comment by CairoLee** [comment]
确认不是问题~ 其实在第 8 步就已经证明没问题了。
第 9 步名字不一致，是因为野外的魔物名称是由刷怪脚本控制的。

prt_fild08（南门）的波利刷怪脚本在 npc/re/mobs/fields/prontera.txt 第 92 行
里面强制指定了召唤出来的 1002 魔物的名字为 Poring，所以程序表现是正确的~

**Comment by CairoLee** [comment]
我也是太久没看这块，愣掉了，一下没反应过来。啧啧啧~

**Comment by CairoLee** [comment]
这个先关闭了~ 有问题再聊~
