### ISSUE TITLE
 ''db/db/re/exp_homun.txt'. 路径重复了

### ISSUE THREAD

**Issue by zhqfdn** [CairoLee/rAthenaCN_Server#16]
[Status]: Done reading '0' entries in 'db/import/homunculus_db.txt'.
[Status]: Done reading '150' levels in _'db/db/re/exp_homun.txt'._
[Status]: Done reading '0' levels in _'db/db/import/exp_homun.txt'._
[Status]: Done reading '82' entries in 'db/homun_skill_tree.txt'.

**Comment by zhqfdn** [comment]
homunculus.cpp ShowStatus db/db/*.txt
* Removed a db_path

1623 行修正
ShowStatus("Done reading '" CL_WHITE "%d" CL_RESET "' levels in '" CL_WHITE "%s/%s" CL_RESET "'.\n", j, db_path, path);

ShowStatus("Done reading '" CL_WHITE "%d" CL_RESET "' levels in '" CL_WHITE "%s" CL_RESET "'.\n", j, path);

**Comment by CairoLee** [comment]
确认问题存在，已经修复，晚一些合并代码

**Comment by CairoLee** [comment]
已经在 e4516bca61c9116506e8f832bd4e9aa713dc3312 修正了此问题
